; https://datatracker.ietf.org/doc/html/rfc9360#name-x509-cose-header-parameters

; x5chain:
; * If a single certificate is conveyed, it is placed in a CBOR byte string.
; * If multiple certificates are conveyed, a CBOR array of byte strings is used, with each certificate being in its own byte string.

COSE_CertHash = [ hashAlg: (int / tstr), hashValue: bstr ]
COSE_X509 = bstr / [ 2*certs: bstr ]

id_cred_x =
{
    ? kid       : 4  => int / bstr,
    ? x5chain   : 33 => COSE_X509,
    ? x5t       : 34 => COSE_CertHash,
}

ead_y = (
  ead_label : int,
  ? ead_value : bstr,
)

EAD_2 = 1* ead_y
EAD_3 = 1* ead_y
EAD_4 = 1* ead_y

map =
{
    ? kid       : 4  => int / bstr,
    ? x5chain   : 33 => COSE_X509,
    ? x5t       : 34 => COSE_CertHash,
}

plaintext_2 =
(
  C_R                 : bstr / -24..23,
  ID_CRED_R           : int / bstr / map,
  Signature_or_MAC_2  : bstr,
  ? EAD_2,
)

plaintext_3 =
(
  ID_CRED_I           : int / bstr / map,
  Signature_or_MAC_3  : bstr,
  ? EAD_3,
)

plaintext_4 =
(
  ? EAD_4,
)
