; https://datatracker.ietf.org/doc/html/rfc9360#name-x509-cose-header-parameters

COSE_CertHash = [ hashAlg: (int / tstr), hashValue: bstr ]
COSE_X509 = bstr / [ 2*certs: bstr ]

; https://datatracker.ietf.org/doc/html/rfc8152#autoid-8

header_map = {
	Generic_Headers,
	* label => values
}

label = int / tstr
values = int / bstr

Generic_Headers = (
    ? 1 => int / tstr,  ; algorithm identifier
    ? 2 => [+label],    ; criticality
    ? 3 => tstr / int,  ; content type
    ? 4 => bstr,        ; key identifier
    ? 5 => bstr,        ; IV
    ? 6 => bstr,        ; Partial IV

    ; Comment out the counter signature since it creates a circular type.
	  ; It is optional, so commenting it out is still conformant.
	  ; ? 7 => COSE_Signature / [+COSE_Signature] ; Counter signature
)

id_cred_x =
{
    ? kid       : 4  => int / bstr,
    ? x5chain   : 33 => COSE_X509,
    ? x5t       : 34 => COSE_CertHash,
}

ead_y = (
  ead_label : int,
  ? ead_value : bstr,
)

EAD_2 = 1* ead_y
EAD_3 = 1* ead_y
EAD_4 = 1* ead_y

map =
{
    ? kid       : 4  => int / bstr,
    ? x5chain   : 33 => COSE_X509,
    ? x5t       : 34 => COSE_CertHash,
}

plaintext_2 =
(
  C_R                 : bstr / -24..23,
  ID_CRED_R           : int / bstr / map,
  Signature_or_MAC_2  : bstr,
  ? EAD_2,
)

plaintext_2b =
(
  C_R                 : bstr / -24..23,
  ? EAD_2,
)

plaintext_3 =
(
  ID_CRED_I           : int / bstr / map,
  Signature_or_MAC_3  : bstr,
  ? EAD_3,
)

plaintext_3a = (
  ID_CRED_PSK : header_map / bstr / -24..23,
  CIPHERTEXT_3B : bstr,
)

plaintext_3b = (
  ? EAD_3,
)

plaintext_4 =
(
  ? EAD_4,
)
