; https://datatracker.ietf.org/doc/html/draft-ietf-lake-edhoc-22#name-cddl-definitions

suites = [ 2** int ] / int

ead_x = (
  ead_label : int,
  ? ead_value : bstr,
)

ead = 1* ead_x
EAD_1 = 1* ead_x

message_1 =
(
  METHOD    : int,
  SUITES_I  : suites,
  G_X       : bstr,
  C_I       : bstr / -24..23,
  ? EAD_1,
)

message_2 =
(
  G_Y_CIPHERTEXT_2 : bstr,
)

message_3 =
(
  CIPHERTEXT_3 : bstr,
)

message_4 =
(
  CIPHERTEXT_4 : bstr,
)

message_error =
(
  ERR_CODE : int,
  ? ERR_INFO : tstr / suites / true ; any
)

info =
(
  info_label    : int,
  context       : bstr,
  length        : uint,
)
